### ISSUE TITLE
The requests module seems to be missing

### ISSUE THREAD

**Issue by mcredstone** [ffmmjj/kairos-face-sdk-python#3]
When I import kairos_face, it tells me that there is no module named requests (line 3, enroll.py). Is that a problem, or just something I've missed?

**Comment by ffmmjj** [comment]
Hi,
I just installed the module in a clean virtualenv with no prior dependencies and it worked fine for me (it detected *requests* as a dependency and installed it properly).
Did you clone this project and run `pip install .` inside the project folder prior to importing the module into your scripts?

**Comment by ffmmjj** [comment]
I didn't get any further feedback from this issue, so I'll close it - feel free to open another one if the problem persists.
