### ISSUE TITLE
Gallery creation

### ISSUE THREAD

**Issue by rishavc13** [ffmmjj/kairos-face-sdk-python#7]
How can we create an empty gallery if we have to?
The _'kairos_face.get_galleries_names_list()'_ only fetches the names of the galleries that already exist. How do I make one before adding any face to it?

**Comment by ffmmjj** [comment]
According to the API documentation in [this link](https://www.kairos.com/docs/api#post-enroll), it's not possible to create a gallery in an isolated way:

> You also need to pick a name for the gallery we are storing your faces in. We`ve called this "gallery_name". If you had used that gallery name before, we will just add your new face to it, otherwise we will create a new gallery for you.

So it seems that you can only list galleries that already have faces attached to them.

**Comment by rishavc13** [comment]
Ok. Thank you so much.
I thought this API was designed by you and so maybe you knew how to do it.

Thank you.

**Comment by ffmmjj** [comment]
No worries - I'll close this issue, then.
